name: spotify-churn-env
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - numpy==2.1.3
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - mlflow==2.19.0
      - joblib==1.4.2
      - dagshub==0.3.23
      - matplotlib==3.9.2
      - seaborn==0.13.2